{{- if .Values.mosquitto.users -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mosquitto.fullname" . }}-users
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
type: Opaque
data:
  accounts.conf: {{ .Values.mosquitto.users | b64enc | quote }}
{{- end -}}
